// -*- coding:utf-8 -*-
// Generated by the Fetch-Leetcode project on the Github
// https://github.com/CJHMPower/Fetch-Leetcode/

// 271 Encode and Decode Strings
// https://leetcode.com//problems/encode-and-decode-strings/description/
// Fetched at 2018-07-24
// Submitted 1 month, 2 weeks ago
// Runtime: 60 ms
// This solution defeats 8.05% java solutions

public class Codec {

  // Encodes a list of strings to a single string.
  public String encode(List<String> strs) {
    String ret = new String();
    for (String s : strs) {
      ret = ret + s.length() + " ";
    }
    int start = ret.length();
    for (String s : strs) {
      ret = ret + s;
    }
    ret = ret + " " + start;
    return ret;
  }

  // Decodes a single string to a list of strings.
  public List<String> decode(String s) {
    int end = s.length() - 1;
    while (end >= 0 && s.charAt(end) != ' ') end--;
    int start = Integer.parseInt(s.substring(end + 1, s.length()));
    int i = 0, j = start, k = 0, len = 0;
    List<String> ret = new ArrayList<>();
    while (k < start) {
      while (k < start && s.charAt(k) != ' ') k++;
      len = Integer.parseInt(s.substring(i, k));
      ret.add(s.substring(j, j + len));
      j = j + len;
      i = k + 1;
      k = i;
    }
    return ret;
  }
}

// Your Codec object will be instantiated and called as such:
// Codec codec = new Codec();
// codec.decode(codec.encode(strs));
