//-*- coding:utf-8 -*-
// Generated by the Fetch-Leetcode project on the Github
// https://github.com/CJHMPower/Fetch-Leetcode/

// 134 Gas Station
// https://leetcode.com//problems/gas-station/description/
// Fetched at 2018-07-24
// Submitted 2 years ago
// Runtime: 9 ms
// This solution defeats 33.11% cpp solutions

class Solution {
 public:
  int canCompleteCircuit(vector<int>& gas, vector<int>& cost) {
    int minremain = gas[0] - cost[0];
    int remain = gas[0] - cost[0];
    if (cost.size() == 1) {
      if (remain < 0) {
        return -1;
      } else {
        return 0;
      }
    }
    for (int i = 1; i < gas.size(); i++) {
      remain += gas[i] - cost[i];
      if (remain < minremain) {
        minremain = remain;
      }
    }
    if (minremain >= 0) {
      return 0;
    }
    for (int i = 1; i < gas.size(); i++) {
      minremain = min(remain, minremain - (gas[i - 1] - cost[i - 1]));
      if (minremain >= 0) {
        return i;
      }
    }
    return -1;
  }
};