//-*- coding:utf-8 -*-
// Generated by the Fetch-Leetcode project on the Github
// https://github.com/CJHMPower/Fetch-Leetcode/

// 80 Remove Duplicates from Sorted Array II
// https://leetcode.com//problems/remove-duplicates-from-sorted-array-ii/description/
// Fetched at 2018-07-24
// Submitted 2 years ago
// Runtime: 20 ms
// This solution defeats 1.17% cpp solutions

class Solution {
 public:
  int removeDuplicates(vector<int>& nums) {
    if (nums.size() < 2) {
      return nums.size();
    }
    for (auto it1 = nums.begin(); it1 != nums.end();) {
      auto it2 = it1;
      while (it2 != nums.end() && *it2 == *it1) {
        it2++;
      }
      if ((int)(it2 - it1) > 2) {
        it1 = nums.erase(it1 + 2, it2);
      } else {
        it1++;
      }
    }
    return nums.size();
  }
};