//-*- coding:utf-8 -*-
// Generated by the Fetch-Leetcode project on the Github
// https://github.com/CJHMPower/Fetch-Leetcode/

// 442 Find All Duplicates in an Array
// https://leetcode.com//problems/find-all-duplicates-in-an-array/description/
// Fetched at 2018-07-24
// Submitted 5 months, 1 week ago
// Runtime: 130 ms
// This solution defeats 10.12% cpp solutions

class Solution {
 public:
  vector<int> findDuplicates(vector<int>& nums) {
    vector<int> ret;
    if (nums.empty()) {
      return ret;
    }
    for (int i = 0; i < nums.size(); i++) {
      if (nums[abs(nums[i]) - 1] > 0) {
        nums[abs(nums[i]) - 1] = -nums[abs(nums[i]) - 1];
      } else {
        ret.push_back(abs(nums[i]));
      }
    }
    return ret;
  }
};