//-*- coding:utf-8 -*-
// Generated by the Fetch-Leetcode project on the Github
// https://github.com/CJHMPower/Fetch-Leetcode/

// 724 Find Pivot Index
// https://leetcode.com//problems/find-pivot-index/description/
// Fetched at 2018-07-24
// Submitted 6 months ago
// Runtime: 37 ms
// This solution defeats 12.92% cpp solutions

class Solution {
 public:
  int pivotIndex(vector<int>& nums) {
    if (nums.size() == 0) {
      return -1;
    }
    vector<int> left_sum(nums.size(), 0);
    vector<int> right_sum(nums.size(), 0);
    for (int i = 1; i < left_sum.size(); i++) {
      left_sum[i] += left_sum[i - 1];
      left_sum[i] += nums[i - 1];
      right_sum[nums.size() - i - 1] += right_sum[nums.size() - i];
      right_sum[nums.size() - i - 1] += nums[nums.size() - i];
    }
    for (int i = 0; i < nums.size(); i++) {
      if (left_sum[i] == right_sum[i]) {
        return i;
      }
    }
    return -1;
  }
};