//-*- coding:utf-8 -*-
// Generated by the Fetch-Leetcode project on the Github
// https://github.com/CJHMPower/Fetch-Leetcode/

// 521 Longest Uncommon Subsequence I
// https://leetcode.com//problems/longest-uncommon-subsequence-i/description/
// Fetched at 2018-07-24
// Submitted 1 year, 1 month ago
// Runtime: 3 ms
// This solution defeats 1.5% cpp solutions

class Solution {
 public:
  int findLUSlength(string a, string b) {
    if (a == b) {
      return -1;
    } else {
      return max(a.size(), b.size());
    }
  }
};