//-*- coding:utf-8 -*-
// Generated by the Fetch-Leetcode project on the Github
// https://github.com/CJHMPower/Fetch-Leetcode/

// 524 Longest Word in Dictionary through Deleting
// https://leetcode.com//problems/longest-word-in-dictionary-through-deleting/description/
// Fetched at 2018-07-24
// Submitted 3 months, 1 week ago
// Runtime: 101 ms
// This solution defeats 2.74% cpp solutions

class Solution {
 public:
  bool is_substring(string &s, string &p) {
    int idx1 = 0, idx2 = 0;
    while (idx2 < p.size()) {
      while (idx1 < s.size() && s[idx1] != p[idx2]) {
        idx1++;
      }
      idx2++;
      if (idx2 >= p.size() && idx1 < s.size()) {
        return true;
      }
      idx1++;
    }
    return !(idx1 >= s.size());
  }
  string findLongestWord(string s, vector<string> &d) {
    sort(d.begin(), d.end(), [](string &a, string &b) {
      return a.size() > b.size() || (a.size() == b.size() && a < b);
    });
    for (auto p : d) {
      if (is_substring(s, p)) {
        return p;
      }
    }
    return "";
  }
};