//-*- coding:utf-8 -*-
// Generated by the Fetch-Leetcode project on the Github
// https://github.com/CJHMPower/Fetch-Leetcode/

// 139 Word Break
// https://leetcode.com//problems/word-break/description/
// Fetched at 2018-07-24
// Submitted 5 months ago
// Runtime: 4 ms
// This solution defeats 76.28% cpp solutions

class Solution {
 public:
  bool wordBreak(string s, vector<string>& wordDict) {
    int n = s.size();
    vector<bool> dp(n + 1, false);
    dp[0] = true;
    for (int i = 1; i <= n; i++) {
      for (string a : wordDict) {
        int j = a.size();
        if (i - j >= 0 && s.substr(i - j, j) == a && dp[i - j] == true) {
          dp[i] = true;
          break;
        }
      }
    }
    return dp.back();
  }
};