//-*- coding:utf-8 -*-
// Generated by the Fetch-Leetcode project on the Github
// https://github.com/CJHMPower/Fetch-Leetcode/

// 370 Range Addition
// https://leetcode.com//problems/range-addition/description/
// Fetched at 2018-07-24
// Submitted 3 months, 4 weeks ago
// Runtime: 96 ms
// This solution defeats 28.02% cpp solutions

class Solution {
 public:
  vector<int> getModifiedArray(int length, vector<vector<int>>& updates) {
    vector<int> start(length, 0);
    vector<int> end(length, 0);
    for (int i = 0; i < updates.size(); i++) {
      start[updates[i][0]] += updates[i][2];
      end[updates[i][1]] += updates[i][2];
    }
    vector<int> ret(length, 0);

    for (int i = 1; i < length; i++) {
      start[i] += start[i - 1];
      end[i] += end[i - 1];
    }

    ret[0] = start[0];
    for (int i = 1; i < length; i++) {
      ret[i] = start[i] - end[i - 1];
    }

    return ret;
  }
};