//-*- coding:utf-8 -*-
// Generated by the Fetch-Leetcode project on the Github
// https://github.com/CJHMPower/Fetch-Leetcode/

// 38 Count and Say
// https://leetcode.com//problems/count-and-say/description/
// Fetched at 2018-07-24
// Submitted 2 years ago
// Runtime: 2 ms
// This solution defeats 19.93% cpp solutions

class Solution {
 public:
  string countAndSay(int n) {
    string result;
    if (n == 1) {
      result = "1";
      return result;
    }
    string recur = countAndSay(n - 1);
    int count = 1;
    char read = recur[0];
    int i = 0;
    while (i < recur.size()) {
      count = 0;
      while (i < recur.size() && recur[i] == read) {
        count++;
        i++;
      }
      result.push_back((char)(count + '0'));
      result.push_back(read);
      if (i >= recur.size()) {
        break;
      }
      read = recur[i];
    }
    return result;
  }
};