// -*- coding:utf-8 -*-
// Generated by the Fetch-Leetcode project on the Github
// https://github.com/CJHMPower/Fetch-Leetcode/

// 874 Backspace String Compare
// https://leetcode.com//problems/backspace-string-compare/description/
// Fetched at 2018-07-24
// Submitted 3 weeks, 3 days ago
// Runtime: 6 ms
// This solution defeats 54.95% java solutions

class Solution {
  String backspace(String S) {
    StringBuilder sb = new StringBuilder();
    Deque<Character> stack = new ArrayDeque<>();
    for (int i = 0; i < S.length(); i++) {
      if (S.charAt(i) != '#') stack.push(S.charAt(i));
      else stack.poll();
    }
    while (stack.size() > 0) {
      sb.append(stack.poll());
    }
    return sb.toString();
  }

  public boolean backspaceCompare(String S, String T) {
    String strS = backspace(S);
    String strT = backspace(T);
    return strS.equals(strT);
  }
}
