//-*- coding:utf-8 -*-
// Generated by the Fetch-Leetcode project on the Github
// https://github.com/CJHMPower/Fetch-Leetcode/

// 441 Arranging Coins
// https://leetcode.com//problems/arranging-coins/description/
// Fetched at 2018-07-24
// Submitted 4 months ago
// Runtime: 40 ms
// This solution defeats 1.24% cpp solutions

class Solution {
 public:
  int arrangeCoins(int n) {
    if (n == 0) {
      return 0;
    }
    int low = 0, high = n - 1;
    long long int mid;
    long long int r;
    while (low <= high) {
      mid = (low + high) / 2;
      r = (mid + 1) * (mid + 2) / 2;
      if (r == n) {
        return mid + 1;
      } else if (r < n) {
        low = mid + 1;
      } else {
        high = mid - 1;
      }
    }
    return low;
  }
};