#-*- coding:utf-8 -*-
#Generated by the Fetch-Leetcode project on the Github
#https://github.com/CJHMPower/Fetch-Leetcode/

#383 Ransom Note
#https://leetcode.com//problems/ransom-note/description/
#Fetched at 2018-07-24
#Submitted 1 year, 10 months ago
#Runtime: 124 ms
#This solution defeats 11.82% python solutions


class Solution(object):
    def canConstruct(self, ransomNote, magazine):
        """

        :type ransomNote: str

        :type magazine: str

        :rtype: bool

        """

        has = [0 for i in range(0, 256)]

        for c in magazine:

            has[ord(c)] += 1

        for c in ransomNote:

            has[ord(c)] -= 1

            if has[ord(c)] < 0:

                return False

        return True
