//-*- coding:utf-8 -*-
// Generated by the Fetch-Leetcode project on the Github
// https://github.com/CJHMPower/Fetch-Leetcode/

// 103 Binary Tree Zigzag Level Order Traversal
// https://leetcode.com//problems/binary-tree-zigzag-level-order-traversal/description/
// Fetched at 2018-07-24
// Submitted 4 months, 4 weeks ago
// Runtime: 5 ms
// This solution defeats 0.89% cpp solutions

/**
 * Definition for a binary tree node.
 * struct TreeNode {
 *     int val;
 *     TreeNode *left;
 *     TreeNode *right;
 *     TreeNode(int x) : val(x), left(NULL), right(NULL) {}
 * };
 */
class Solution {
 public:
  void zigzagLevelOrder(TreeNode* root, int i, vector<deque<int>>& ret) {
    if (root == NULL) {
      return;
    }
    if (i >= ret.size()) {
      ret.push_back(deque<int>{root->val});
    } else if (i % 2 == 0) {
      ret[i].push_back(root->val);
    } else {
      ret[i].push_front(root->val);
    }

    zigzagLevelOrder(root->left, i + 1, ret);
    zigzagLevelOrder(root->right, i + 1, ret);
  }
  vector<vector<int>> zigzagLevelOrder(TreeNode* root) {
    vector<deque<int>> temp;
    zigzagLevelOrder(root, 0, temp);
    vector<vector<int>> ret;
    for (auto q : temp) {
      ret.push_back(vector<int>());
      while (!q.empty()) {
        ret.back().push_back(q.front());
        q.pop_front();
      }
    }
    return ret;
  }
};