//-*- coding:utf-8 -*-
// Generated by the Fetch-Leetcode project on the Github
// https://github.com/CJHMPower/Fetch-Leetcode/

// 115 Distinct Subsequences
// https://leetcode.com//problems/distinct-subsequences/description/
// Fetched at 2018-07-24
// Submitted 1 year, 10 months ago
// Runtime: 6 ms
// This solution defeats 8.62% cpp solutions

class Solution {
 public:
  int numDistinct(string s, string t) {
    vector<int> cur(t.size() + 1, 0);
    cur[0] = 1;
    for (int i = 1; i <= s.size(); i++) {
      for (int j = cur.size() - 1; j >= 0; j--) {
        if (s[i - 1] == t[j - 1]) {
          cur[j] += cur[j - 1];
        }
      }
    }
    return cur.back();
  }
};