//-*- coding:utf-8 -*-
// Generated by the Fetch-Leetcode project on the Github
// https://github.com/CJHMPower/Fetch-Leetcode/

// 151 Reverse Words in a String
// https://leetcode.com//problems/reverse-words-in-a-string/description/
// Fetched at 2018-07-24
// Submitted 1 year, 10 months ago
// Runtime: 9 ms
// This solution defeats 7.52% cpp solutions

class Solution {
 public:
  void reverseWords(string &s) {
    reverse(s.begin(), s.end());
    auto it1 = s.begin();
    auto it2 = it1;
    while (it1 != s.end()) {
      auto it3 = it1;
      while (*it3 == ' ') {
        it3++;
      }
      it1 = s.erase(it1, it3);
      it2 = it1;
      while (it2 != s.end() && *it2 != ' ') {
        it2++;
      }
      reverse(it1, it2);
      it1 = it2;
      if (it2 == s.end()) {
        break;
      }
      while (it2 != s.end() && *it2 == ' ') {
        it2++;
      }
      if (it2 != s.end())
        it1 = s.erase(it1 + 1, it2);
      else {
        it1 = s.erase(it1, it2);
      }
      it2 = it1;
    }
  }
};