//-*- coding:utf-8 -*-
// Generated by the Fetch-Leetcode project on the Github
// https://github.com/CJHMPower/Fetch-Leetcode/

// 560 Subarray Sum Equals K
// https://leetcode.com//problems/subarray-sum-equals-k/description/
// Fetched at 2018-07-24
// Submitted 3 months, 1 week ago
// Runtime: 45 ms
// This solution defeats 31.39% cpp solutions

class Solution {
 public:
  int subarraySum(vector<int>& nums, int k) {
    if (nums.empty()) {
      return 0;
    }

    int ret = 0;
    int sum = 0;
    map<int, int> hash;
    hash[0] = 1;
    for (int i = 0; i < nums.size(); i++) {
      sum += nums[i];
      if (hash.find(sum) != hash.end()) {
        hash[sum]++;
      } else {
        hash[sum] = 1;
      }
      if (hash.find(sum - k) != hash.end()) {
        ret += hash[sum - k];
      }
    }
    if (k == 0) {
      ret -= nums.size();
    }
    return ret;
  }
};