//-*- coding:utf-8 -*-
// Generated by the Fetch-Leetcode project on the Github
// https://github.com/CJHMPower/Fetch-Leetcode/

// 365 Water and Jug Problem
// https://leetcode.com//problems/water-and-jug-problem/description/
// Fetched at 2018-07-24
// Submitted 2 years ago
// Runtime: 0 ms
// This solution defeats 100.0% cpp solutions

class Solution {
 public:
  int gcd(int a, int b) {
    if (a % b == 0) {
      return b;
    } else {
      return gcd(b, a % b);
    }
  }
  bool canMeasureWater(int x, int y, int z) {
    if (z == 0 || z == x + y) return true;
    if (z > x + y) return false;
    if (x == 0) return z == y;
    if (y == 0) return z == x;
    if (x == y) return z == x;
    int y_in = (y > x) ? y : x;
    int x_in = (y > x) ? x : y;
    int r = y_in % x_in;
    if (r == 0) {
      return z % x_in == 0;
    } else {
      return z % gcd(r, x_in) == 0;
    }
  }
};