//-*- coding:utf-8 -*-
// Generated by the Fetch-Leetcode project on the Github
// https://github.com/CJHMPower/Fetch-Leetcode/

// 462 Minimum Moves to Equal Array Elements II
// https://leetcode.com//problems/minimum-moves-to-equal-array-elements-ii/description/
// Fetched at 2018-07-24
// Submitted 3 months, 2 weeks ago
// Runtime: 19 ms
// This solution defeats 10.65% cpp solutions

class Solution {
 public:
  int minMoves2(vector<int>& nums) {
    sort(nums.begin(), nums.end());
    int target = nums[nums.size() / 2];
    int ret = 0;
    for (auto a : nums) {
      ret += abs(a - target);
    }
    return ret;
  }
};