//-*- coding:utf-8 -*-
// Generated by the Fetch-Leetcode project on the Github
// https://github.com/CJHMPower/Fetch-Leetcode/

// 537 Complex Number Multiplication
// https://leetcode.com//problems/complex-number-multiplication/description/
// Fetched at 2018-07-24
// Submitted 3 months ago
// Runtime: 3 ms
// This solution defeats 1.07% cpp solutions

class Solution {
 public:
  pair<int, int> complex(string a) {
    int i = 0;
    pair<int, int> ret;
    while (i < a.size() && a[i] != '+') {
      i++;
    }
    ret.first = stoi(a.substr(0, i));
    ret.second = stoi(a.substr(i + 1, a.size() - i - 2));
    return ret;
  }
  string complexNumberMultiply(string a, string b) {
    pair<int, int> a_complex = complex(a);
    pair<int, int> b_complex = complex(b);
    int real =
        a_complex.first * b_complex.first - a_complex.second * b_complex.second;
    int unreal =
        a_complex.second * b_complex.first + a_complex.first * b_complex.second;
    return to_string(real) + "+" + to_string(unreal) + "i";
  }
};