//-*- coding:utf-8 -*-
// Generated by the Fetch-Leetcode project on the Github
// https://github.com/CJHMPower/Fetch-Leetcode/

// 112 Path Sum
// https://leetcode.com//problems/path-sum/description/
// Fetched at 2018-07-24
// Submitted 2 years ago
// Runtime: 12 ms
// This solution defeats 1.89% cpp solutions

/**
 * Definition for a binary tree node.
 * struct TreeNode {
 *     int val;
 *     TreeNode *left;
 *     TreeNode *right;
 *     TreeNode(int x) : val(x), left(NULL), right(NULL) {}
 * };
 */
class Solution {
 public:
  bool hasPathSum(TreeNode* root, int sum) {
    if (root == nullptr) {
      return false;
    }
    queue<TreeNode*> Q;
    Q.push(root);
    TreeNode* temp = nullptr;
    while (!Q.empty()) {
      temp = Q.front();
      Q.pop();
      if (temp->left != nullptr) {
        Q.push(temp->left);
        temp->left->val += temp->val;
      }
      if (temp->right != nullptr) {
        Q.push(temp->right);
        temp->right->val += temp->val;
      } else if (temp->left == nullptr && temp->right == nullptr) {
        if (temp->val == sum) {
          return true;
        }
      }
    }
    return false;
  }
};