#-*- coding:utf-8 -*-
#Generated by the Fetch-Leetcode project on the Github
#https://github.com/CJHMPower/Fetch-Leetcode/ 

#175 Combine Two Tables
#https://leetcode.com//problems/combine-two-tables/description/
#Fetched at 2018-07-24
#Submitted 1 month, 2 weeks ago
#Runtime: 212 ms
#This solution defeats 93.31% mysql solutions

# Write your MySQL query statement below
SELECT Person.FirstName, Person.LastName, Address.City, Address.State FROM Person LEFT JOIN Address ON Person.PersonId=Address.PersonId 