//-*- coding:utf-8 -*-
// Generated by the Fetch-Leetcode project on the Github
// https://github.com/CJHMPower/Fetch-Leetcode/

// 26 Remove Duplicates from Sorted Array
// https://leetcode.com//problems/remove-duplicates-from-sorted-array/description/
// Fetched at 2018-07-24
// Submitted 1 year, 10 months ago
// Runtime: 79 ms
// This solution defeats 4.23% cpp solutions

class Solution {
 public:
  int removeDuplicates(vector<int>& nums) {
    if (nums.size() < 2) {
      return nums.size();
    }
    auto slow = nums.begin();
    auto fast = nums.begin() + 1;
    while (fast != nums.end()) {
      while (fast != nums.end() && *slow == *fast) {
        fast++;
      }
      slow = nums.erase(slow, fast - 1) + 1;
      if (slow == nums.end()) {
        break;
      }
      fast = slow + 1;
    }
    return nums.size();
  }
};