//-*- coding:utf-8 -*-
// Generated by the Fetch-Leetcode project on the Github
// https://github.com/CJHMPower/Fetch-Leetcode/

// 121 Best Time to Buy and Sell Stock
// https://leetcode.com//problems/best-time-to-buy-and-sell-stock/description/
// Fetched at 2018-07-24
// Submitted 5 months ago
// Runtime: 7 ms
// This solution defeats 17.19% cpp solutions

class Solution {
 public:
  int maxProfit(vector<int>& prices) {
    if (prices.size() < 2) {
      return 0;
    }
    int lowest = prices[0];
    int ret = 0;
    for (int i = 1; i < prices.size(); i++) {
      if (prices[i] - lowest > ret) {
        ret = prices[i] - lowest;
      }
      if (prices[i] < lowest) {
        lowest = prices[i];
      }
    }
    return ret;
  }
};