//-*- coding:utf-8 -*-
// Generated by the Fetch-Leetcode project on the Github
// https://github.com/CJHMPower/Fetch-Leetcode/

// 88 Merge Sorted Array
// https://leetcode.com//problems/merge-sorted-array/description/
// Fetched at 2018-07-24
// Submitted 2 years ago
// Runtime: 8 ms
// This solution defeats 1.98% cpp solutions

class Solution {
 public:
  void merge(vector<int>& nums1, int m, vector<int>& nums2, int n) {
    for (int i = m, j = 0; j < n; i++, j++) {
      nums1[i] = nums2[j];
    }
    sort(nums1.begin(), nums1.begin() + m + n);
  }
};