//-*- coding:utf-8 -*-
// Generated by the Fetch-Leetcode project on the Github
// https://github.com/CJHMPower/Fetch-Leetcode/

// 53 Maximum Subarray
// https://leetcode.com//problems/maximum-subarray/description/
// Fetched at 2018-07-24
// Submitted 2 years ago
// Runtime: 12 ms
// This solution defeats 8.14% cpp solutions

class Solution {
 public:
#define INF pow(10, 7)
  int maxSubArray(vector<int>& a) {
    if (a.empty()) {
      return 0;
    }
    vector<int> dp(a.size());
    dp[0] = a[0];
    int result = dp[0];
    for (int i = 1; i < a.size(); i++) {
      dp[i] = max(dp[i - 1] + a[i], a[i]);
      if (dp[i] > result) {
        result = dp[i];
      }
    }
    return result;
  }
};