//-*- coding:utf-8 -*-
// Generated by the Fetch-Leetcode project on the Github
// https://github.com/CJHMPower/Fetch-Leetcode/

// 27 Remove Element
// https://leetcode.com//problems/remove-element/description/
// Fetched at 2018-07-24
// Submitted 2 years ago
// Runtime: 5 ms
// This solution defeats 0.15% cpp solutions

class Solution {
 public:
  int removeElement(vector<int>& nums, int val) {
    for (auto it = nums.begin(); it != nums.end();) {
      if (*it == val) {
        it = nums.erase(it);
      } else {
        it++;
      }
    }
    return nums.size();
  }
};