//-*- coding:utf-8 -*-
// Generated by the Fetch-Leetcode project on the Github
// https://github.com/CJHMPower/Fetch-Leetcode/

// 453 Minimum Moves to Equal Array Elements
// https://leetcode.com//problems/minimum-moves-to-equal-array-elements/description/
// Fetched at 2018-07-24
// Submitted 4 months ago
// Runtime: 53 ms
// This solution defeats 1.35% cpp solutions

class Solution {
 public:
  int minMoves(vector<int>& nums) {
    if (nums.size() == 1) {
      return 0;
    }
    long long int sum = 0;
    int min_val = INT_MAX;
    for (auto n : nums) {
      sum += n;
      min_val = min(n, min_val);
    }
    int n = nums.size();
    long long int k = sum - min_val - (n - 2) * min_val;
    return (k * n - sum) / (n - 1);
  }
};