//-*- coding:utf-8 -*-
// Generated by the Fetch-Leetcode project on the Github
// https://github.com/CJHMPower/Fetch-Leetcode/

// 84 Largest Rectangle in Histogram
// https://leetcode.com//problems/largest-rectangle-in-histogram/description/
// Fetched at 2018-07-24
// Submitted 1 year, 10 months ago
// Runtime: 22 ms
// This solution defeats 12.73% cpp solutions

class Solution {
 public:
  int largestRectangleArea(vector<int>& heights) {
    if (heights.empty()) {
      return 0;
    }
    int maxArea = 0;
    heights.push_back(0);
    stack<int> peak;
    for (int i = 0; i < heights.size(); i++) {
      if (peak.empty() || heights[i] >= heights[peak.top()]) {
        peak.push(i);
      } else {
        int tp = peak.top();
        peak.pop();
        maxArea =
            max(maxArea, heights[tp] * (peak.empty() ? i : i - 1 - peak.top()));
        i--;
      }
    }
    return maxArea;
  }
};