//-*- coding:utf-8 -*-
// Generated by the Fetch-Leetcode project on the Github
// https://github.com/CJHMPower/Fetch-Leetcode/

// 85 Maximal Rectangle
// https://leetcode.com//problems/maximal-rectangle/description/
// Fetched at 2018-07-24
// Submitted 1 year, 10 months ago
// Runtime: 36 ms
// This solution defeats 5.07% cpp solutions

class Solution {
 public:
  int largestRectangleArea(vector<int>& heights) {
    if (heights.empty()) {
      return 0;
    }
    int maxArea = 0;
    heights.push_back(0);
    stack<int> peak;
    for (int i = 0; i < heights.size(); i++) {
      if (peak.empty() || heights[i] >= heights[peak.top()]) {
        peak.push(i);
      } else {
        int tp = peak.top();
        peak.pop();
        maxArea =
            max(maxArea, heights[tp] * (peak.empty() ? i : i - 1 - peak.top()));
        i--;
      }
    }
    return maxArea;
  }
  int maximalRectangle(vector<vector<char>>& matrix) {
    if (matrix.empty()) {
      return 0;
    }
    int m = matrix.size();
    int n = matrix[0].size();
    int maximal = 0;
    vector<int> height(m);
    for (int j = 0; j < n; j++) {
      for (int i = 0; i < m; i++) {
        int k = j;
        while (k < n && matrix[i][k] == '1') {
          k++;
        }
        height[i] = k - j;
      }
      int ret = largestRectangleArea(height);
      maximal = max(maximal, ret);
    }
    return maximal;
  }
};