//-*- coding:utf-8 -*-
// Generated by the Fetch-Leetcode project on the Github
// https://github.com/CJHMPower/Fetch-Leetcode/

// 541 Reverse String II
// https://leetcode.com//problems/reverse-string-ii/description/
// Fetched at 2018-07-24
// Submitted 2 months, 3 weeks ago
// Runtime: 15 ms
// This solution defeats 1.41% cpp solutions

class Solution {
 public:
  string reverseStr(string s, int k) {
    for (int i = 0; i < s.size(); i += 2 * k) {
      reverse(s.begin() + i, s.begin() + min(i + k, int(s.end() - s.begin())));
    }
    return s;
  }
};