//-*- coding:utf-8 -*-
// Generated by the Fetch-Leetcode project on the Github
// https://github.com/CJHMPower/Fetch-Leetcode/

// 171 Excel Sheet Column Number
// https://leetcode.com//problems/excel-sheet-column-number/description/
// Fetched at 2018-07-24
// Submitted 2 years ago
// Runtime: 8 ms
// This solution defeats 1.91% cpp solutions

class Solution {
 public:
  int titleToNumber(string s) {
    int result = 0;
    int i = s.size() - 1;
    while (i >= 0) {
      result += (int)(s[i] - 'A' + 1) * pow(26, s.size() - 1 - i);
      i--;
    }
    return result;
  }
};