//-*- coding:utf-8 -*-
// Generated by the Fetch-Leetcode project on the Github
// https://github.com/CJHMPower/Fetch-Leetcode/

// 467 Unique Substrings in Wraparound String
// https://leetcode.com//problems/unique-substrings-in-wraparound-string/description/
// Fetched at 2018-07-24
// Submitted 3 months, 2 weeks ago
// Runtime: 13 ms
// This solution defeats 10.09% cpp solutions

class Solution {
 public:
  char next(char a) {
    if (a == 'z') {
      return 'a';
    } else {
      return char(a + 1);
    }
  }
  int findSubstringInWraproundString(string p) {
    if (p.empty()) {
      return 0;
    }
    vector<int> record(26, 0);
    int ret = 0;
    vector<int> dp(p.size(), 0);
    dp[0] = 1;

    for (int i = 1; i < p.size(); i++) {
      if (p[i] == next(p[i - 1])) {
        dp[i] = dp[i - 1] + 1;
      } else {
        dp[i] = 1;
      }
    }
    for (int i = 0; i < dp.size(); i++) {
      if (dp[i] > record[p[i] - 'a']) {
        ret += (dp[i] - record[p[i] - 'a']);
        record[p[i] - 'a'] = dp[i];
      }
    }
    return ret;
  }
};