//-*- coding:utf-8 -*-
// Generated by the Fetch-Leetcode project on the Github
// https://github.com/CJHMPower/Fetch-Leetcode/

// 342 Power of Four
// https://leetcode.com//problems/power-of-four/description/
// Fetched at 2018-07-24
// Submitted 2 years, 1 month ago
// Runtime: 8 ms

class Solution {
 public:
  bool isPowerOfFour(int num) {
    if (num <= 0) {
      return false;
    }
    if (((num - 1) & num) == 0) {
      if (sqrtf(num) == sqrt(num)) {
        if (((int)sqrt(num) & ((int)sqrt(num) - 1)) == 0) return true;
      }
    }
    return false;
  }
};