//-*- coding:utf-8 -*-
// Generated by the Fetch-Leetcode project on the Github
// https://github.com/CJHMPower/Fetch-Leetcode/

// 292 Nim Game
// https://leetcode.com//problems/nim-game/description/
// Fetched at 2018-07-24
// Submitted 2 years, 1 month ago
// Runtime: 0 ms
// This solution defeats 100.0% cpp solutions

class Solution {
 public:
  bool canWinNim(int n) {
    if (n % 4 == 0)
      return false;
    else
      return true;
  }
};