#-*- coding:utf-8 -*-
#Generated by the Fetch-Leetcode project on the Github
#https://github.com/CJHMPower/Fetch-Leetcode/

#782 Jewels and Stones
#https://leetcode.com//problems/jewels-and-stones/description/
#Fetched at 2018-07-24
#Submitted 5 months ago
#Runtime: 40 ms
#This solution defeats 99.37% python3 solutions


class Solution:
    def numJewelsInStones(self, J, S):
        """
        :type J: str
        :type S: str
        :rtype: int
        """
        hash = set(J)
        ret = 0
        for c in S:
            if c in hash:
                ret += 1
        return ret
