//-*- coding:utf-8 -*-
// Generated by the Fetch-Leetcode project on the Github
// https://github.com/CJHMPower/Fetch-Leetcode/

// 344 Reverse String
// https://leetcode.com//problems/reverse-string/description/
// Fetched at 2018-07-24
// Submitted 5 months ago
// Runtime: 10 ms
// This solution defeats 2.5% cpp solutions

class Solution {
 public:
  string reverseString(string s) {
    int low = 0, high = s.size() - 1;
    while (low < high) {
      swap(s[low], s[high]);
      low++;
      high--;
    }
    return s;
  }
};