//-*- coding:utf-8 -*-
// Generated by the Fetch-Leetcode project on the Github
// https://github.com/CJHMPower/Fetch-Leetcode/

// 179 Largest Number
// https://leetcode.com//problems/largest-number/description/
// Fetched at 2018-07-24
// Submitted 2 years ago
// Runtime: 20 ms
// This solution defeats 3.15% cpp solutions

class Solution {
 public:
  string largestNumber(vector<int>& nums) {
    string result;
    if (nums.empty()) {
      return result;
    }
    auto f = [](int a, int b) -> bool {
      string sa = to_string(a);
      string sb = to_string(b);
      long long int linka = stoll(sa + sb);
      long long int linkb = stoll(sb + sa);
      return linka > linkb;
    };
    sort(nums.begin(), nums.end(), f);
    for (auto v : nums) {
      result = result + to_string(v);
    }
    auto it = result.begin();
    while (result.size() > 1 && *it == '0') {
      it = result.erase(it);
    }
    return result;
  }
};