//-*- coding:utf-8 -*-
// Generated by the Fetch-Leetcode project on the Github
// https://github.com/CJHMPower/Fetch-Leetcode/

// 695 Max Area of Island
// https://leetcode.com//problems/max-area-of-island/description/
// Fetched at 2018-07-24
// Submitted 2 months, 4 weeks ago
// Runtime: 28 ms
// This solution defeats 5.64% cpp solutions

class Solution {
 public:
  int DFS(vector<vector<int>>& grid, int i, int j) {
    if (i < 0 || i >= grid.size() || j < 0 || j >= grid[0].size() ||
        grid[i][j] != 1) {
      return 0;
    }
    int ret = 1;
    grid[i][j] = 0;
    ret += DFS(grid, i - 1, j);
    ret += DFS(grid, i + 1, j);
    ret += DFS(grid, i, j + 1);
    ret += DFS(grid, i, j - 1);
    return ret;
  }
  int maxAreaOfIsland(vector<vector<int>>& grid) {
    int ret = 0;
    for (int i = 0; i < grid.size(); i++) {
      for (int j = 0; j < grid[i].size(); j++) {
        if (grid[i][j] == 1) {
          ret = max(ret, DFS(grid, i, j));
        }
      }
    }
    return ret;
  }
};