//-*- coding:utf-8 -*-
// Generated by the Fetch-Leetcode project on the Github
// https://github.com/CJHMPower/Fetch-Leetcode/

// 397 Integer Replacement
// https://leetcode.com//problems/integer-replacement/description/
// Fetched at 2018-07-24
// Submitted 1 year, 10 months ago
// Runtime: 9 ms
// This solution defeats 3.51% cpp solutions

class Solution {
 public:
  int integerReplacement(int n) {
    if (n == INT_MAX) {
      return 32;
    }
    if (n == 1) {
      return 0;
    }
    if ((n & (n - 1)) == 0) {
      return log2(n);
    }
    if (n % 2 == 0) {
      return integerReplacement(n / 2) + 1;
    } else {
      return min(integerReplacement(n - 1), integerReplacement(n + 1)) + 1;
    }
  }
};