//-*- coding:utf-8 -*-
// Generated by the Fetch-Leetcode project on the Github
// https://github.com/CJHMPower/Fetch-Leetcode/

// 186 Reverse Words in a String II
// https://leetcode.com//problems/reverse-words-in-a-string-ii/description/
// Fetched at 2018-07-24
// Submitted 4 months, 4 weeks ago
// Runtime: 38 ms
// This solution defeats 2.81% cpp solutions

class Solution {
 public:
  void reverseWords(vector<char>& str) {
    reverse(str.begin(), str.end());
    int i = 0;
    int low = i;
    while (i < str.size()) {
      if (str[i] == ' ') {
        reverse(str.begin() + low, str.begin() + i);
        i++;
        low = i;
      }
      i++;
    }
    reverse(str.begin() + low, str.begin() + i);
  }
};