// -*- coding:utf-8 -*-
// Generated by the Fetch-Leetcode project on the Github
// https://github.com/CJHMPower/Fetch-Leetcode/

// 712 Minimum ASCII Delete Sum for Two Strings
// https://leetcode.com//problems/minimum-ascii-delete-sum-for-two-strings/description/
// Fetched at 2018-07-24
// Submitted 1 month, 1 week ago
// Runtime: 24 ms
// This solution defeats 57.12% java solutions

class Solution {
  public int minimumDeleteSum(String s1, String s2) {
    int m = s1.length(), n = s2.length();
    int[][] dp = new int[m + 1][n + 1];
    dp[0][0] = 0;
    for (int i = 1; i <= m; i++) dp[i][0] = dp[i - 1][0] + (byte) (s1.charAt(i - 1));
    for (int j = 1; j <= n; j++) dp[0][j] += dp[0][j - 1] + (byte) (s2.charAt(j - 1));
    for (int i = 1; i <= m; i++) {
      for (int j = 1; j <= n; j++) {
        if (s1.charAt(i - 1) == s2.charAt(j - 1)) dp[i][j] = dp[i - 1][j - 1];
        else
          dp[i][j] =
              Math.min(
                  dp[i - 1][j] + (byte) (s1.charAt(i - 1)),
                  dp[i][j - 1] + (byte) (s2.charAt(j - 1)));
      }
    }
    return dp[m][n];
  }
}
