//-*- coding:utf-8 -*-
// Generated by the Fetch-Leetcode project on the Github
// https://github.com/CJHMPower/Fetch-Leetcode/

// 191 Number of 1 Bits
// https://leetcode.com//problems/number-of-1-bits/description/
// Fetched at 2018-07-24
// Submitted 2 years ago
// Runtime: 8 ms
// This solution defeats 1.32% cpp solutions

class Solution {
 public:
  int hammingWeight(uint32_t n) {
    int count = 0;
    while (n != 0) {
      n = (n & (n - 1));
      count++;
    }
    return count;
  }
};