//-*- coding:utf-8 -*-
// Generated by the Fetch-Leetcode project on the Github
// https://github.com/CJHMPower/Fetch-Leetcode/

// 276 Paint Fence
// https://leetcode.com//problems/paint-fence/description/
// Fetched at 2018-07-24
// Submitted 4 months, 4 weeks ago
// Runtime: 2 ms

class Solution {
 public:
  int numWays(int n, int k) {
    if (n == 0 || k == 0) {
      return 0;
    }
    if (k < 2) {
      if (n < 3) {
        return 1;
      } else {
        return 0;
      }
    }
    int r0 = k;
    int r1 = 0;
    int temp;
    for (int i = 1; i < n; i++) {
      temp = r0;
      r0 = (k - 1) * (r1 + r0);
      r1 = temp;
    }
    return r0 + r1;
  }
};