//-*- coding:utf-8 -*-
// Generated by the Fetch-Leetcode project on the Github
// https://github.com/CJHMPower/Fetch-Leetcode/

// 210 Course Schedule II
// https://leetcode.com//problems/course-schedule-ii/description/
// Fetched at 2018-07-24
// Submitted 2 years, 1 month ago
// Runtime: 28 ms
// This solution defeats 8.87% cpp solutions

class Solution {
 public:
  vector<int> findOrder(int numCourses, vector<pair<int, int>>& prerequisites) {
    vector<int> result;
    vector<vector<int>> graph(numCourses);
    vector<int> indegree(numCourses, 0);
    for (auto it = prerequisites.begin(); it != prerequisites.end(); it++) {
      graph[it->second].push_back(it->first);
      indegree[it->first]++;
    }
    queue<int> Q;
    for (int i = 0; i < numCourses; i++) {
      if (indegree[i] == 0) {
        Q.push(i);
        result.push_back(i);
      }
    }
    int counter = 0;
    while (!Q.empty()) {
      int u = Q.front();
      Q.pop();
      counter++;
      for (int i = 0; i < graph[u].size(); i++)
        if (--indegree[graph[u][i]] == 0) {
          Q.push(graph[u][i]);
          result.push_back(graph[u][i]);
        }
    }
    if (counter != numCourses) {
      result.clear();
    }
    return result;
  }
};