//-*- coding:utf-8 -*-
// Generated by the Fetch-Leetcode project on the Github
// https://github.com/CJHMPower/Fetch-Leetcode/

// 100 Same Tree
// https://leetcode.com//problems/same-tree/description/
// Fetched at 2018-07-24
// Submitted 2 years ago
// Runtime: 2 ms

/**
 * Definition for a binary tree node.
 * struct TreeNode {
 *     int val;
 *     TreeNode *left;
 *     TreeNode *right;
 *     TreeNode(int x) : val(x), left(NULL), right(NULL) {}
 * };
 */
class Solution {
 public:
  bool isSameTree(TreeNode* p, TreeNode* q) {
    if (p == nullptr && q == nullptr) {
      return true;
    }
    if ((p == nullptr && q != nullptr) || (p != nullptr && q == nullptr)) {
      return false;
    }
    return (p->val == q->val && isSameTree(p->left, q->left) &&
            isSameTree(p->right, q->right));
  }
};