//-*- coding:utf-8 -*-
// Generated by the Fetch-Leetcode project on the Github
// https://github.com/CJHMPower/Fetch-Leetcode/

// 349 Intersection of Two Arrays
// https://leetcode.com//problems/intersection-of-two-arrays/description/
// Fetched at 2018-07-24
// Submitted 2 years, 2 months ago
// Runtime: 12 ms
// This solution defeats 2.13% cpp solutions

class Solution {
 public:
  vector<int> intersection(vector<int>& a, vector<int>& b) {
    vector<int> c;
    sort(a.begin(), a.end());
    sort(b.begin(), b.end());
    int i = 0, j = 0;
    while (i < a.size() && j < b.size()) {
      if (a[i] < b[j]) {
        do
          i++;
        while (i < a.size() && a[i] < b[j]);
      } else if (a[i] > b[j]) {
        do
          j++;
        while (j < b.size() && a[i] > b[j]);
      }
      if (i >= a.size() || j >= b.size()) break;
      if (a[i] == b[j]) {
        if (c.empty() || a[i] != c[c.size() - 1]) c.push_back(a[i]);
        i++;
        j++;
      }
    }
    return c;
  }
};