//-*- coding:utf-8 -*-
// Generated by the Fetch-Leetcode project on the Github
// https://github.com/CJHMPower/Fetch-Leetcode/

// 278 First Bad Version
// https://leetcode.com//problems/first-bad-version/description/
// Fetched at 2018-07-24
// Submitted 2 years, 1 month ago
// Runtime: 0 ms
// This solution defeats 100.0% cpp solutions

// Forward declaration of isBadVersion API.
bool isBadVersion(int version);

class Solution {
 public:
  long long int firstBadVersion(long long int n) {
    long long int low = 1, high = n;
    long long int mid;
    while (high - low >= 1) {
      mid = (low + high) / 2;
      if (isBadVersion(mid) == true) {
        high = mid - 1;
      } else {
        low = mid + 1;
      }
    }
    if (isBadVersion(low) == true) {
      return low;
    } else
      return high + 1;
  }
};