//-*- coding:utf-8 -*-
// Generated by the Fetch-Leetcode project on the Github
// https://github.com/CJHMPower/Fetch-Leetcode/

// 646 Maximum Length of Pair Chain
// https://leetcode.com//problems/maximum-length-of-pair-chain/description/
// Fetched at 2018-07-24
// Submitted 1 month, 2 weeks ago
// Runtime: 28 ms
// This solution defeats 78.25% cpp solutions

class Solution {
 public:
  int findLongestChain(vector<vector<int>>& pairs) {
    sort(pairs.begin(), pairs.end());
    vector<int> dp(pairs.size(), 0);
    dp[0] = 1;
    int j;
    for (int i = 1; i < pairs.size(); i++) {
      j = i - 1;
      while (j >= 0 && pairs[j][1] >= pairs[i][0]) j--;
      if (j >= 0) {
        dp[i] = dp[j] + 1;
      } else {
        dp[i] = 1;
      }
    }
    return dp[pairs.size() - 1];
  }
};