//-*- coding:utf-8 -*-
// Generated by the Fetch-Leetcode project on the Github
// https://github.com/CJHMPower/Fetch-Leetcode/

// 495 Teemo Attacking
// https://leetcode.com//problems/teemo-attacking/description/
// Fetched at 2018-07-24
// Submitted 3 months, 2 weeks ago
// Runtime: 62 ms
// This solution defeats 2.15% cpp solutions

class Solution {
 public:
  int findPoisonedDuration(vector<int>& timeSeries, int duration) {
    if (timeSeries.empty()) {
      return 0;
    }
    int todo = 0, undo = 0;
    int ret = 0, i = 0;
    while (i < timeSeries.size()) {
      todo = timeSeries[i];
      undo = todo + duration;
      while (i + 1 < timeSeries.size() && undo > timeSeries[i + 1]) {
        undo = timeSeries[i + 1] + duration;
        i++;
      }
      ret += (undo - todo);
      i++;
    }

    return ret;
  }
};