//-*- coding:utf-8 -*-
// Generated by the Fetch-Leetcode project on the Github
// https://github.com/CJHMPower/Fetch-Leetcode/

// 145 Binary Tree Postorder Traversal
// https://leetcode.com//problems/binary-tree-postorder-traversal/description/
// Fetched at 2018-07-24
// Submitted 2 years ago
// Runtime: 0 ms
// This solution defeats 100.0% cpp solutions

/**
 * Definition for a binary tree node.
 * struct TreeNode {
 *     int val;
 *     TreeNode *left;
 *     TreeNode *right;
 *     TreeNode(int x) : val(x), left(NULL), right(NULL) {}
 * };
 */
class Solution {
 public:
  vector<int> postorderTraversal(TreeNode* root) {
    vector<int> result;
    stack<TreeNode*> Q;
    if (root == nullptr) {
      return result;
    }
    Q.push(root);
    while (!Q.empty()) {
      if (Q.top()->left == nullptr && Q.top()->right == nullptr) {
        result.push_back(Q.top()->val);
        Q.pop();
      } else if (Q.top()->left != nullptr) {
        TreeNode* temp = Q.top();
        Q.push(temp->left);
        temp->left = nullptr;
      } else if (Q.top()->right != nullptr) {
        TreeNode* temp = Q.top();
        Q.push(temp->right);
        temp->right = nullptr;
      }
    }
    return result;
  }
};