//-*- coding:utf-8 -*-
// Generated by the Fetch-Leetcode project on the Github
// https://github.com/CJHMPower/Fetch-Leetcode/

// 76 Minimum Window Substring
// https://leetcode.com//problems/minimum-window-substring/description/
// Fetched at 2018-07-24
// Submitted 2 years ago
// Runtime: 12 ms
// This solution defeats 53.59% cpp solutions

class Solution {
 public:
  string minWindow(string s, string t) {
    vector<int> map(128, 0);
    for (auto c : t) map[c]++;
    int counter = t.size(), begin = 0, end = 0, d = INT_MAX, head = 0;
    while (end < s.size()) {
      if (map[s[end++]]-- > 0) counter--;  // in t
      while (counter == 0) {               // valid
        if (end - begin < d) d = end - (head = begin);
        if (map[s[begin++]]++ == 0) counter++;  // make it invalid
      }
    }
    return d == INT_MAX ? "" : s.substr(head, d);
  }
};