//-*- coding:utf-8 -*-
// Generated by the Fetch-Leetcode project on the Github
// https://github.com/CJHMPower/Fetch-Leetcode/

// 263 Ugly Number
// https://leetcode.com//problems/ugly-number/description/
// Fetched at 2018-07-24
// Submitted 2 years, 1 month ago
// Runtime: 8 ms
// This solution defeats 3.09% cpp solutions

class Solution {
 public:
  bool isUgly(int num) {
    if (num == 0) {
      return false;
    }
    if (num == 1) {
      return true;
    }
    while (num % 2 == 0) {
      num /= 2;
    }
    while (num % 3 == 0) {
      num /= 3;
    }
    while (num % 5 == 0) {
      num /= 5;
    }
    if (num != 1) {
      return false;
    }
    return true;
  }
};