//-*- coding:utf-8 -*-
// Generated by the Fetch-Leetcode project on the Github
// https://github.com/CJHMPower/Fetch-Leetcode/

// 122 Best Time to Buy and Sell Stock II
// https://leetcode.com//problems/best-time-to-buy-and-sell-stock-ii/description/
// Fetched at 2018-07-24
// Submitted 2 years ago
// Runtime: 8 ms
// This solution defeats 5.14% cpp solutions

class Solution {
 public:
  int maxProfit(vector<int>& prices) {
    if (prices.empty()) {
      return 0;
    }
    int prof = 0;
    for (int i = 1; i < prices.size(); i++) {
      prof += max(0, prices[i] - prices[i - 1]);
    }
    return prof;
  }
};