//-*- coding:utf-8 -*-
// Generated by the Fetch-Leetcode project on the Github
// https://github.com/CJHMPower/Fetch-Leetcode/

// 114 Flatten Binary Tree to Linked List
// https://leetcode.com//problems/flatten-binary-tree-to-linked-list/description/
// Fetched at 2018-07-24
// Submitted 2 years ago
// Runtime: 8 ms
// This solution defeats 12.3% cpp solutions

/**
 * Definition for a binary tree node.
 * struct TreeNode {
 *     int val;
 *     TreeNode *left;
 *     TreeNode *right;
 *     TreeNode(int x) : val(x), left(NULL), right(NULL) {}
 * };
 */
class Solution {
 public:
  void flatten(TreeNode* root) {
    stack<TreeNode*> pre;
    vector<TreeNode*> result;
    if (root == nullptr) {
      return;
    }
    pre.push(root);
    result.push_back(root);
    while (!pre.empty()) {
      if (pre.top()->left != nullptr) {
        TreeNode* temp = pre.top();
        result.push_back(pre.top()->left);
        pre.push(pre.top()->left);
        temp->left = nullptr;
      } else if (pre.top()->right != nullptr) {
        TreeNode* temp = pre.top();
        result.push_back(pre.top()->right);
        pre.push(pre.top()->right);
        temp->right = nullptr;
      } else if (pre.top()->left == nullptr && pre.top()->right == nullptr) {
        pre.pop();
      }
    }
    for (int i = 0; i < result.size() - 1; i++) {
      result[i]->right = result[i + 1];
      result[i]->left = nullptr;
    }
    result[result.size() - 1]->left = nullptr;
    result[result.size() - 1]->right = nullptr;
  }
};