//-*- coding:utf-8 -*-
// Generated by the Fetch-Leetcode project on the Github
// https://github.com/CJHMPower/Fetch-Leetcode/

// 392 Is Subsequence
// https://leetcode.com//problems/is-subsequence/description/
// Fetched at 2018-07-24
// Submitted 1 year, 10 months ago
// Runtime: 82 ms
// This solution defeats 9.93% cpp solutions

class Solution {
 public:
  bool isSubsequence(string s, string t) {
    if (s.size() > t.size()) {
      return false;
    }
    while (true) {
      if (s.empty()) {
        return true;
      }
      auto it = find(t.begin(), t.end(), s[0]);
      if (it == t.end()) {
        return false;
      }
      s.erase(s.begin());
      t.erase(t.begin(), it + 1);
    }
    return true;
  }
};