//-*- coding:utf-8 -*-
// Generated by the Fetch-Leetcode project on the Github
// https://github.com/CJHMPower/Fetch-Leetcode/

// 87 Scramble String
// https://leetcode.com//problems/scramble-string/description/
// Fetched at 2018-07-24
// Submitted 1 year, 10 months ago
// Runtime: 13 ms
// This solution defeats 17.33% cpp solutions

class Solution {
 public:
  bool isScramble(string s1, string s2) {
    if (s1 == s2) {
      return true;
    }
    string st1 = s1, st2 = s2;
    sort(st1.begin(), st1.end());
    sort(st2.begin(), st2.end());
    if (st1 != st2) {
      return false;
    }
    string spre1, sback1, spre2, sback2;
    for (int i = 1; i < s1.size(); i++) {
      spre1 = s1.substr(0, i);
      sback1 = s1.substr(i, s1.size() - i);
      spre2 = s2.substr(0, i);
      sback2 = s2.substr(i, s2.size() - i);
      if (isScramble(spre1, spre2) && isScramble(sback1, sback2)) {
        return true;
      }
      spre2 = s2.substr(0, s2.size() - i);
      sback2 = s2.substr(s2.size() - i, i);
      if (isScramble(spre1, sback2) && isScramble(spre2, sback1)) {
        return true;
      }
    }
    return false;
  }
};