//-*- coding:utf-8 -*-
// Generated by the Fetch-Leetcode project on the Github
// https://github.com/CJHMPower/Fetch-Leetcode/

// 187 Repeated DNA Sequences
// https://leetcode.com//problems/repeated-dna-sequences/description/
// Fetched at 2018-07-24
// Submitted 1 year, 10 months ago
// Runtime: 440 ms

class Solution {
 public:
  vector<string> findRepeatedDnaSequences(string s) {
    vector<string> result;
    if (s.size() <= 10) {
      return result;
    }
    map<string, int> hash;
    map<string, int> exist;
    string str;
    for (int i = 0; i <= s.size() - 10; i++) {
      str = s.substr(i, 10);
      if (hash[str] > 0 && exist[str] <= 0) {
        result.push_back(str);
        exist[str]++;
      }
      hash[str]++;
    }
    return result;
  }
};