#-*- coding:utf-8 -*-
#Generated by the Fetch-Leetcode project on the Github
#https://github.com/CJHMPower/Fetch-Leetcode/

#387 First Unique Character in a String
#https://leetcode.com//problems/first-unique-character-in-a-string/description/
#Fetched at 2018-07-24
#Submitted 1 year, 10 months ago
#Runtime: 264 ms
#This solution defeats 10.94% python solutions


class Solution(object):
    def firstUniqChar(self, s):
        """

        :type s: str

        :rtype: int

        """

        has = list()

        for i in range(0, 26):

            has.append(0)

        for c in s:

            has[ord(c) - ord('a')] += 1

        length = len(s)

        for i in range(0, length):

            if has[ord(s[i]) - ord('a')] <= 1:

                return i

        return -1
