//-*- coding:utf-8 -*-
// Generated by the Fetch-Leetcode project on the Github
// https://github.com/CJHMPower/Fetch-Leetcode/

// 242 Valid Anagram
// https://leetcode.com//problems/valid-anagram/description/
// Fetched at 2018-07-24
// Submitted 2 years, 1 month ago
// Runtime: 80 ms
// This solution defeats 1.44% cpp solutions

class Solution {
 public:
  bool isAnagram(string s, string t) {
    sort(s.begin(), s.end());
    sort(t.begin(), t.end());
    return s == t;
  }
};