//-*- coding:utf-8 -*-
// Generated by the Fetch-Leetcode project on the Github
// https://github.com/CJHMPower/Fetch-Leetcode/

// 81 Search in Rotated Sorted Array II
// https://leetcode.com//problems/search-in-rotated-sorted-array-ii/description/
// Fetched at 2018-07-24
// Submitted 2 years ago
// Runtime: 8 ms
// This solution defeats 5.28% cpp solutions

class Solution {
 public:
  bool search(vector<int>& nums, int target) {
    for (int i = 0; i < nums.size(); i++) {
      if (target == nums[i]) {
        return true;
      }
    }
    return false;
  }
};