//-*- coding:utf-8 -*-
// Generated by the Fetch-Leetcode project on the Github
// https://github.com/CJHMPower/Fetch-Leetcode/

// 575 Distribute Candies
// https://leetcode.com//problems/distribute-candies/description/
// Fetched at 2018-07-24
// Submitted 2 months ago
// Runtime: 438 ms

class Solution {
 public:
  int distributeCandies(vector<int>& candies) {
    map<int, int> hash;
    for (auto a : candies) {
      if (hash.find(a) == hash.end()) hash[a] = 0;
      hash[a]++;
    }
    int n = candies.size() / 2;
    return min(n, int(hash.size()));
  }
};