//-*- coding:utf-8 -*-
// Generated by the Fetch-Leetcode project on the Github
// https://github.com/CJHMPower/Fetch-Leetcode/

// 316 Remove Duplicate Letters
// https://leetcode.com//problems/remove-duplicate-letters/description/
// Fetched at 2018-07-24
// Submitted 1 year, 10 months ago
// Runtime: 3 ms
// This solution defeats 43.13% cpp solutions

class Solution {
 public:
  string removeDuplicateLetters(string s) {
    vector<int> count(26, 0);
    for (auto c : s) {
      count[c - 'a']++;
    }
    stack<char> stk;
    vector<int> visited(26, false);
    for (auto c : s) {
      count[c - 'a']--;
      if (visited[c - 'a'] == true) {
        continue;
      }
      while (!stk.empty() && stk.top() > c && count[stk.top() - 'a'] > 0) {
        visited[stk.top() - 'a'] = false;
        stk.pop();
      }
      stk.push(c);
      visited[c - 'a'] = true;
    }
    string result;
    while (!stk.empty()) {
      result = stk.top() + result;
      stk.pop();
    }
    return result;
  }
};