//-*- coding:utf-8 -*-
// Generated by the Fetch-Leetcode project on the Github
// https://github.com/CJHMPower/Fetch-Leetcode/

// 167 Two Sum II - Input array is sorted
// https://leetcode.com//problems/two-sum-ii---input-array-is-sorted/description/
// Fetched at 2018-07-24
// Submitted 1 year, 10 months ago
// Runtime: 6 ms
// This solution defeats 9.58% cpp solutions

class Solution {
 public:
  int binary_search(vector<int>& nums, int low, int high, int target) {
    int mid = (low + high) / 2;
    while (high >= low) {
      mid = (low + high) / 2;
      if (nums[mid] == target) {
        return mid;
      } else if (nums[mid] < target) {
        low = mid + 1;
      } else {
        high = mid - 1;
      }
    }
    return -1;
  }
  vector<int> twoSum(vector<int>& numbers, int target) {
    int idx;
    for (int i = 0; i < numbers.size(); i++) {
      idx = binary_search(numbers, i + 1, numbers.size() - 1,
                          target - numbers[i]);
      if (idx > 0) {
        return {i + 1, idx + 1};
      }
    }
    return {0, 0};
  }
};