//-*- coding:utf-8 -*-
// Generated by the Fetch-Leetcode project on the Github
// https://github.com/CJHMPower/Fetch-Leetcode/

// 422 Valid Word Square
// https://leetcode.com//problems/valid-word-square/description/
// Fetched at 2018-07-24
// Submitted 4 months ago
// Runtime: 16 ms
// This solution defeats 4.76% cpp solutions

class Solution {
 public:
  bool validWordSquare(vector<string>& words) {
    int i = 0;
    while (i < words.size()) {
      for (int j = 0; j < words[i].size(); j++) {
        if (j >= words.size() || i >= words[j].size()) {
          return false;
        }
        if (words[j][i] != words[i][j]) {
          return false;
        }
      }
      i++;
    }
    return true;
  }
};