//-*- coding:utf-8 -*-
// Generated by the Fetch-Leetcode project on the Github
// https://github.com/CJHMPower/Fetch-Leetcode/

// 532 K-diff Pairs in an Array
// https://leetcode.com//problems/k-diff-pairs-in-an-array/description/
// Fetched at 2018-07-24
// Submitted 5 months, 4 weeks ago
// Runtime: 45 ms
// This solution defeats 17.45% cpp solutions

class Solution {
 public:
  int findPairs(vector<int>& nums, int k) {
    if (k < 0) {
      return 0;
    }
    map<int, int> count;
    for (int i = 0; i < nums.size(); i++) {
      if (count.find(nums[i]) == count.end()) {
        count[nums[i]] = 1;
      } else {
        count[nums[i]] += 1;
      }
    }
    int ret = 0;
    if (k == 0) {
      for (auto it = count.begin(); it != count.end(); it++) {
        if (it->second > 1) {
          ret += 1;
        }
      }
      return ret;
    }
    for (auto it = count.begin(); it != count.end(); it++) {
      int a = it->first;
      if (count.find(a + k) != count.end()) {
        ret += 1;
      }
    }
    return ret;
  }
};