//-*- coding:utf-8 -*-
// Generated by the Fetch-Leetcode project on the Github
// https://github.com/CJHMPower/Fetch-Leetcode/

// 233 Number of Digit One
// https://leetcode.com//problems/number-of-digit-one/description/
// Fetched at 2018-07-24
// Submitted 2 years, 1 month ago
// Runtime: 0 ms
// This solution defeats 100.0% cpp solutions

class Solution {
 public:
  long long int countDigitOne(long long int n) {
    if (n <= 0) {
      return 0;
    }
    if (n < 10) {
      return 1;
    }
    if (n == 10) {
      return 2;
    }
    int bit = int(logf(n) / logf(10));
    if (pow(10, bit) > n) {
      bit--;
    }
    long long int sum = bit * pow(10, bit - 1) + 1;
    const long long int nmax = n / pow(10, bit);
    if (nmax == 1) {
      sum = sum + countDigitOne(n - pow(10, bit)) + n - pow(10, bit);
    } else {
      long long int remain = n - nmax * pow(10, bit);
      sum = sum + countDigitOne(remain) + pow(10, bit) - 1 +
            (nmax - 1) * (bit * pow(10, bit - 1));
    }
    return sum;
  }
};