//-*- coding:utf-8 -*-
// Generated by the Fetch-Leetcode project on the Github
// https://github.com/CJHMPower/Fetch-Leetcode/

// 150 Evaluate Reverse Polish Notation
// https://leetcode.com//problems/evaluate-reverse-polish-notation/description/
// Fetched at 2018-07-24
// Submitted 1 year, 10 months ago
// Runtime: 19 ms
// This solution defeats 5.16% cpp solutions

class Solution {
 public:
  int Eval(int a, int b, char c) {
    switch (c) {
      case '+':
        return a + b;
      case '-':
        return a - b;
      case '*':
        return a * b;
      case '/':
        return a / b;
    }
    return 0;
  }
  int evalRPN(vector<string>& tokens) {
    stack<string> oper;
    stack<int> nums;
    for (auto s : tokens) {
      if (isdigit(s[0]) || (s.size() > 1 && isdigit(s[1]) == true)) {
        nums.push(stoi(s));
      } else {
        int a = nums.top();
        nums.pop();
        int b = nums.top();
        nums.pop();
        nums.push(Eval(b, a, s[0]));
      }
    }
    return nums.top();
  }
};