//-*- coding:utf-8 -*-
// Generated by the Fetch-Leetcode project on the Github
// https://github.com/CJHMPower/Fetch-Leetcode/

// 28 Implement strStr()
// https://leetcode.com//problems/implement-strstr()/description/
// Fetched at 2018-07-24
// Submitted 2 years ago
// Runtime: 4 ms
// This solution defeats 97.84% cpp solutions

class Solution {
 public:
  int strStr(string haystack, string needle) {
    if (needle.empty()) {
      return 0;
    }
    int i = 0;
    int j = needle.size();
    while (j <= haystack.size()) {
      if (haystack.substr(i, j - i) == needle) {
        return i;
      }
      i++;
      j++;
    }
    return -1;
  }
};