//-*- coding:utf-8 -*-
// Generated by the Fetch-Leetcode project on the Github
// https://github.com/CJHMPower/Fetch-Leetcode/

// 69 Sqrt(x)
// https://leetcode.com//problems/sqrt(x)/description/
// Fetched at 2018-07-24
// Submitted 2 years ago
// Runtime: 16 ms
// This solution defeats 22.24% cpp solutions

class Solution {
 public:
  int mySqrt(int x) {
    long long int low = 0;
    long long int high = (long long int)(x);
    long long int mid;
    while (high >= low) {
      mid = (low + high) / 2;
      if (mid * mid <= x && (mid + 1) * (mid + 1) > x) {
        return mid;
      } else if (mid * mid < x) {
        low = mid + 1;
      } else {
        high = mid - 1;
      }
    }
    return (low + high) / 2;
  }
};