//-*- coding:utf-8 -*-
// Generated by the Fetch-Leetcode project on the Github
// https://github.com/CJHMPower/Fetch-Leetcode/

// 294 Flip Game II
// https://leetcode.com//problems/flip-game-ii/description/
// Fetched at 2018-07-24
// Submitted 3 months ago
// Runtime: 78 ms
// This solution defeats 22.51% cpp solutions

class Solution {
 public:
  bool canWin(string s) {
    if (s.empty()) {
      return false;
    }
    for (int i = 0; i < s.size() - 1; i++) {
      if (s[i] == '+' && s[i + 1] == '+') {
        s[i] = '-';
        s[i + 1] = '-';
        if (canWin(s) == false) {
          return true;
        }
        s[i] = '+';
        s[i + 1] = '+';
      }
    }
    return false;
  }
};