//-*- coding:utf-8 -*-
// Generated by the Fetch-Leetcode project on the Github
// https://github.com/CJHMPower/Fetch-Leetcode/

// 492 Construct the Rectangle
// https://leetcode.com//problems/construct-the-rectangle/description/
// Fetched at 2018-07-24
// Submitted 3 months, 2 weeks ago
// Runtime: 3 ms
// This solution defeats 31.33% cpp solutions

class Solution {
 public:
  int int_sqrt(int area) {
    int low = 1, high = area;
    long long int mid, val;
    while (low <= high) {
      mid = (low + high) / 2;
      val = mid * mid;
      if (val == area) {
        return mid;
      } else if (val < area) {
        low = mid + 1;
      } else {
        high = mid - 1;
      }
    }
    mid = (low + high) / 2;
    return mid;
  }
  vector<int> constructRectangle(int area) {
    int start = int_sqrt(area);
    while (start > 1 && area % start != 0) {
      start--;
    }
    return vector<int>{area / start, start};
  }
};