//-*- coding:utf-8 -*-
// Generated by the Fetch-Leetcode project on the Github
// https://github.com/CJHMPower/Fetch-Leetcode/

// 204 Count Primes
// https://leetcode.com//problems/count-primes/description/
// Fetched at 2018-07-24
// Submitted 2 years, 1 month ago
// Runtime: 308 ms
// This solution defeats 9.82% cpp solutions

class Solution {
 public:
  int countPrimes(int n) {
    if (n < 3) {
      return 0;
    }
    vector<bool> nums(n, false);
    nums[0] = 0;
    nums[1] = 0;
    int count = 0;
    for (int i = 2; i * i < n; i++) {
      if (!nums[i]) {
        for (int j = i; i * j < n; j++) {
          nums[i * j] = true;
        }
      }
    }
    for (int i = 2; i < n; i++) {
      if (nums[i] == false) {
        count++;
      }
    }
    return count;
  }
};