//-*- coding:utf-8 -*-
// Generated by the Fetch-Leetcode project on the Github
// https://github.com/CJHMPower/Fetch-Leetcode/

// 657 Judge Route Circle
// https://leetcode.com//problems/judge-route-circle/description/
// Fetched at 2018-07-24
// Submitted 5 months, 4 weeks ago
// Runtime: 19 ms
// This solution defeats 3.48% cpp solutions

class Solution {
 public:
  bool judgeCircle(string moves) {
    int left = 0, right = 0, up = 0, down = 0;
    for (auto a : moves) {
      switch (a) {
        case 'L':
          left++;
          break;
        case 'R':
          right++;
          break;
        case 'U':
          up++;
          break;
        case 'D':
          down++;
          break;
      }
    }
    return left == right && up == down;
  }
};