//-*- coding:utf-8 -*-
// Generated by the Fetch-Leetcode project on the Github
// https://github.com/CJHMPower/Fetch-Leetcode/

// 415 Add Strings
// https://leetcode.com//problems/add-strings/description/
// Fetched at 2018-07-24
// Submitted 4 months, 1 week ago
// Runtime: 16 ms
// This solution defeats 4.27% cpp solutions

class Solution {
 public:
  string addStrings(string num1, string num2) {
    string result = "";
    if (num1.size() < num2.size()) {
      swap(num1, num2);
    }
    int m = num1.size() - 1;
    int n = num2.size() - 1;
    int bit = 0;
    int now = 0;
    while (n >= 0) {
      now = (num1[m] - '0') + (num2[n] - '0') + bit;
      bit = now / 10;
      now = now % 10;
      result = to_string(now) + result;
      n--;
      m--;
    }
    while (m >= 0) {
      now = bit + (num1[m] - '0');
      bit = now / 10;
      now = now % 10;
      result = to_string(now) + result;
      m--;
    }
    if (bit != 0) {
      result = to_string(bit) + result;
    }
    return result;
  }
};