//-*- coding:utf-8 -*-
// Generated by the Fetch-Leetcode project on the Github
// https://github.com/CJHMPower/Fetch-Leetcode/

// 561 Array Partition I
// https://leetcode.com//problems/array-partition-i/description/
// Fetched at 2018-07-24
// Submitted 2 months ago
// Runtime: 83 ms
// This solution defeats 2.63% cpp solutions

class Solution {
 public:
  int arrayPairSum(vector<int>& nums) {
    sort(nums.begin(), nums.end());
    int sum = 0;
    for (int i = 0; i < nums.size(); i += 2) {
      sum += nums[i];
    }
    return sum;
  }
};