//-*- coding:utf-8 -*-
// Generated by the Fetch-Leetcode project on the Github
// https://github.com/CJHMPower/Fetch-Leetcode/

// 369 Plus One Linked List
// https://leetcode.com//problems/plus-one-linked-list/description/
// Fetched at 2018-07-24
// Submitted 4 months ago
// Runtime: 6 ms

/**
 * Definition for singly-linked list.
 * struct ListNode {
 *     int val;
 *     ListNode *next;
 *     ListNode(int x) : val(x), next(NULL) {}
 * };
 */
class Solution {
 public:
  ListNode *plusOne(ListNode *head) {
    if (head == NULL) {
      return NULL;
    }
    ListNode *p = head;
    ListNode *pre = NULL;
    while (p->next) {
      if (p->val != 9) {
        pre = p;
      }
      p = p->next;
    }
    if (p->val != 9) {
      p->val += 1;
      return head;
    } else if (pre != NULL) {
      pre->val += 1;
      ListNode *t = pre->next;
      while (t != NULL) {
        t->val = 0;
        t = t->next;
      }
    } else {
      ListNode *node = (ListNode *)malloc(sizeof(ListNode));
      node->val = 1;
      node->next = head;
      pre = head;
      head = node;
      while (pre) {
        pre->val = 0;
        pre = pre->next;
      }
    }
    return head;
  }
};