//-*- coding:utf-8 -*-
// Generated by the Fetch-Leetcode project on the Github
// https://github.com/CJHMPower/Fetch-Leetcode/

// 217 Contains Duplicate
// https://leetcode.com//problems/contains-duplicate/description/
// Fetched at 2018-07-24
// Submitted 2 years, 1 month ago
// Runtime: 36 ms
// This solution defeats 4.43% cpp solutions

class Solution {
 public:
  bool containsDuplicate(vector<int>& nums) {
    sort(nums.begin(), nums.end());
    if (nums.empty()) {
      return false;
    }
    int start = nums[0];
    for (int i = 1; i < nums.size(); i++) {
      if (nums[i] == start) {
        return true;
      }
      start = nums[i];
    }
    return false;
  }
};