//-*- coding:utf-8 -*-
// Generated by the Fetch-Leetcode project on the Github
// https://github.com/CJHMPower/Fetch-Leetcode/

// 473 Matchsticks to Square
// https://leetcode.com//problems/matchsticks-to-square/description/
// Fetched at 2018-07-24
// Submitted 3 months, 2 weeks ago
// Runtime: 951 ms
// This solution defeats 6.59% cpp solutions

class Solution {
 public:
  bool dfs(vector<int>& nums, int start, int a, int b, int c, int d) {
    if (start >= nums.size()) {
      return true;
    }
    if (a >= nums[start] && dfs(nums, start + 1, a - nums[start], b, c, d)) {
      return true;
    }
    if (b >= nums[start] && dfs(nums, start + 1, a, b - nums[start], c, d)) {
      return true;
    }
    if (c >= nums[start] && dfs(nums, start + 1, a, b, c - nums[start], d)) {
      return true;
    }
    if (d >= nums[start] && dfs(nums, start + 1, a, b, c, d - nums[start])) {
      return true;
    }
    return false;
  }
  bool makesquare(vector<int>& nums) {
    if (nums.empty()) {
      return false;
    }
    int sum = accumulate(nums.begin(), nums.end(), 0);
    if (sum % 4 != 0) {
      return false;
    }
    int a = sum / 4;
    return dfs(nums, 0, a, a, a, a);
  }
};