//-*- coding:utf-8 -*-
// Generated by the Fetch-Leetcode project on the Github
// https://github.com/CJHMPower/Fetch-Leetcode/

// 319 Bulb Switcher
// https://leetcode.com//problems/bulb-switcher/description/
// Fetched at 2018-07-24
// Submitted 2 years, 1 month ago
// Runtime: 0 ms
// This solution defeats 100.0% cpp solutions

class Solution {
 public:
  int bulbSwitch(int n) {
    if (n < 0)
      return 0;
    else
      return (int)sqrt(n);
  }
};