//-*- coding:utf-8 -*-
// Generated by the Fetch-Leetcode project on the Github
// https://github.com/CJHMPower/Fetch-Leetcode/

// 434 Number of Segments in a String
// https://leetcode.com//problems/number-of-segments-in-a-string/description/
// Fetched at 2018-07-24
// Submitted 4 months ago
// Runtime: 2 ms

class Solution {
 public:
  int countSegments(string s) {
    int count = 0;
    bool space = true;
    for (int i = 0; i < s.size(); i++) {
      if (space == true && s[i] != ' ') {
        count++;
        space = false;
      } else if (s[i] == ' ') {
        space = true;
      }
    }
    return count;
  }
};