//-*- coding:utf-8 -*-
// Generated by the Fetch-Leetcode project on the Github
// https://github.com/CJHMPower/Fetch-Leetcode/

// 455 Assign Cookies
// https://leetcode.com//problems/assign-cookies/description/
// Fetched at 2018-07-24
// Submitted 4 months, 2 weeks ago
// Runtime: 53 ms
// This solution defeats 4.78% cpp solutions

class Solution {
 public:
  int findContentChildren(vector<int>& g, vector<int>& s) {
    int count = 0;
    sort(g.begin(), g.end());
    sort(s.begin(), s.end());
    int i = 0, j = 0;
    while (j < s.size() && i < g.size()) {
      while (j < s.size() && s[j] < g[i]) {
        j++;
      }
      if (j >= s.size()) {
        break;
      } else {
        count++;
        i++;
        j++;
      }
    }
    return count;
  }
};