//-*- coding:utf-8 -*-
// Generated by the Fetch-Leetcode project on the Github
// https://github.com/CJHMPower/Fetch-Leetcode/

// 190 Reverse Bits
// https://leetcode.com//problems/reverse-bits/description/
// Fetched at 2018-07-24
// Submitted 2 years ago
// Runtime: 8 ms
// This solution defeats 3.32% cpp solutions

class Solution {
 public:
  uint32_t reverseBits(uint32_t n) {
    int result = 0;
    int i = 0;
    while (n) {
      if (n % 2 != 0) {
        result += pow(2, 31 - i);
      }
      i++;
      n = n >> 1;
    }
    return result;
  }
};