#-*- coding:utf-8 -*-
#Generated by the Fetch-Leetcode project on the Github
#https://github.com/CJHMPower/Fetch-Leetcode/

#384 Shuffle an Array
#https://leetcode.com//problems/shuffle-an-array/description/
#Fetched at 2018-07-24
#Submitted 1 year, 10 months ago
#Runtime: 996 ms


class Solution(object):
    def __init__(self, nums):
        """

        

        :type nums: List[int]

        :type size: int

        """

        self.data = nums[:]

    def reset(self):
        """

        Resets the array to its original configuration and return it.

        :rtype: List[int]

        """

        return self.data

    def shuffle(self):
        """

        Returns a random shuffling of the array.

        :rtype: List[int]

        """

        import random

        import math

        temp = self.data[:]

        random.shuffle(temp)

        return temp


# Your Solution object will be instantiated and called as such:

# obj = Solution(nums)

# param_1 = obj.reset()

# param_2 = obj.shuffle()
