//-*- coding:utf-8 -*-
// Generated by the Fetch-Leetcode project on the Github
// https://github.com/CJHMPower/Fetch-Leetcode/

// 268 Missing Number
// https://leetcode.com//problems/missing-number/description/
// Fetched at 2018-07-24
// Submitted 2 years, 1 month ago
// Runtime: 36 ms
// This solution defeats 3.11% cpp solutions

class Solution {
 public:
  int missingNumber(vector<int>& nums) {
    int n = nums.size();
    int result = 0;
    for (int i = 0; i < nums.size(); i++) {
      result = result ^ nums[i];
    }
    for (int i = 0; i <= n; i++) {
      result = result ^ i;
    }
    return result;
  }
};