// -*- coding:utf-8 -*-
// Generated by the Fetch-Leetcode project on the Github
// https://github.com/CJHMPower/Fetch-Leetcode/

// 606 Construct String from Binary Tree
// https://leetcode.com//problems/construct-string-from-binary-tree/description/
// Fetched at 2018-07-24
// Submitted 1 month ago
// Runtime: 29 ms
// This solution defeats 14.12% java solutions

/**
 * Definition for a binary tree node. public class TreeNode { int val; TreeNode left; TreeNode
 * right; TreeNode(int x) { val = x; } }
 */
class Solution {
  public String tree2str(TreeNode t) {
    if (t == null) return new String("");
    StringBuilder ret = new StringBuilder(t.val + "");
    String leftstr = tree2str(t.left);
    String rightstr = tree2str(t.right);
    if (t.left != null || t.right != null) {
      ret = ret.append("(" + leftstr + ")");
      if (t.right != null) ret = ret.append("(" + rightstr + ")");
      else ret = ret.append(rightstr);
    }
    return ret.toString();
  }
}
