//-*- coding:utf-8 -*-
// Generated by the Fetch-Leetcode project on the Github
// https://github.com/CJHMPower/Fetch-Leetcode/

// 463 Island Perimeter
// https://leetcode.com//problems/island-perimeter/description/
// Fetched at 2018-07-24
// Submitted 5 months, 4 weeks ago
// Runtime: 197 ms
// This solution defeats 1.3% cpp solutions

class Solution {
 public:
  int islandPerimeter(vector<vector<int>>& grid) {
    if (grid.empty()) {
      return 0;
    }
    int perimeter = 0;
    for (int i = 0; i < grid.size(); i++) {
      for (int j = 0; j < grid[0].size(); j++) {
        if (grid[i][j] != 0) {
          if (i - 1 < 0 || grid[i - 1][j] == 0) {
            perimeter++;
          }
          if (i + 1 >= grid.size() || grid[i + 1][j] == 0) {
            perimeter++;
          }
          if (j - 1 < 0 || grid[i][j - 1] == 0) {
            perimeter++;
          }
          if (j + 1 >= grid[0].size() || grid[i][j + 1] == 0) {
            perimeter++;
          }
        }
      }
    }
    return perimeter;
  }
};