//-*- coding:utf-8 -*-
// Generated by the Fetch-Leetcode project on the Github
// https://github.com/CJHMPower/Fetch-Leetcode/

// 8 String to Integer (atoi)
// https://leetcode.com//problems/string-to-integer-(atoi)/description/
// Fetched at 2018-07-24
// Submitted 2 years ago
// Runtime: 12 ms
// This solution defeats 94.8% cpp solutions

class Solution {
 public:
  int myAtoi(string str) {
    if (str.empty()) {
      return 0;
    }
    int i = 0;
    while (i < str.size() && str[i] == ' ') {
      i++;
    }
    if (i >= str.size()) {
      return 0;
    }
    int minus = 1;
    if (i < str.size() && str[i] == '-') {
      minus = -1;
    }
    if (str[i] != '+' && str[i] != '-' && !(str[i] >= '0' && str[i] <= '9')) {
      return 0;
    }
    if (str[i] == '+' || str[i] == '-') {
      i++;
    }
    long long int num = 0;
    while (i < str.size()) {
      if (str[i] < '0' || str[i] > '9') {
        if (minus == 1 && num > INT_MAX) {
          return INT_MAX;
        }
        if (minus == -1 && num < (signed int)(INT_MIN)) {
          return INT_MIN;
        }
        return num;
      } else {
        num = 10 * num + minus * (str[i] - '0');
      }
      if (minus == 1 && num > INT_MAX) {
        return INT_MAX;
      }
      if (minus == -1 && num < (signed int)(INT_MIN)) {
        return INT_MIN;
      }
      i++;
    }
    return num;
  }
};