//-*- coding:utf-8 -*-
// Generated by the Fetch-Leetcode project on the Github
// https://github.com/CJHMPower/Fetch-Leetcode/

// 412 Fizz Buzz
// https://leetcode.com//problems/fizz-buzz/description/
// Fetched at 2018-07-24
// Submitted 1 year, 9 months ago
// Runtime: 6 ms
// This solution defeats 1.58% cpp solutions

class Solution {
 public:
  vector<string> fizzBuzz(int n) {
    vector<string> result;
    for (int i = 1; i <= n; i++) {
      if (i % 3 == 0) {
        if (i % 5 == 0) {
          result.push_back("FizzBuzz");
        } else {
          result.push_back("Fizz");
        }
      } else if (i % 5 == 0) {
        result.push_back("Buzz");
      } else {
        result.push_back(to_string(i));
      }
    }
    return result;
  }
};