//-*- coding:utf-8 -*-
// Generated by the Fetch-Leetcode project on the Github
// https://github.com/CJHMPower/Fetch-Leetcode/

// 3 Longest Substring Without Repeating Characters
// https://leetcode.com//problems/longest-substring-without-repeating-characters/description/
// Fetched at 2018-07-24
// Submitted 2 years ago
// Runtime: 16 ms
// This solution defeats 78.92% cpp solutions

class Solution {
 public:
  int lengthOfLongestSubstring(string s) {
    int str_len = s.size();
    int l = 0;
    int len = 0;
    int max_len = 0;
    int char_indexes[128];
    memset(char_indexes, -1, sizeof(char_indexes));
    char c = '\0';
    int prev_indx_of_cur_char = 0;
    for (int r = 0; r < str_len; ++r) {
      c = s[r];
      prev_indx_of_cur_char = char_indexes[c];
      if (prev_indx_of_cur_char >= l) {
        l = prev_indx_of_cur_char + 1;
        len = r - l + 1;
      } else {
        ++len;
      }
      char_indexes[c] = r;
      max_len = max(len, max_len);
    }
    return max_len;
  }
};