//-*- coding:utf-8 -*-
// Generated by the Fetch-Leetcode project on the Github
// https://github.com/CJHMPower/Fetch-Leetcode/

// 331 Verify Preorder Serialization of a Binary Tree
// https://leetcode.com//problems/verify-preorder-serialization-of-a-binary-tree/description/
// Fetched at 2018-07-24
// Submitted 2 years, 2 months ago
// Runtime: 6 ms
// This solution defeats 6.75% cpp solutions

class Solution {
 public:
  bool isValidSerialization(string preorder) {
    if (preorder.empty()) return false;
    if (preorder == "#") return true;
    if (preorder[0] == '#' && preorder.size() > 1) return false;
    int leaf = 0;
    int comma = 0;
    int unleaf = 0;
    for (int i = 0; i < preorder.size(); i++) {
      if (preorder[i] == ',') {
        comma++;
        unleaf = comma - leaf;
      } else if (preorder[i] == '#')
        leaf++;
      else
        continue;
      if (leaf - unleaf >= 1 && i != preorder.size() - 1) return false;
    }
    if (unleaf + 1 == leaf)
      return true;
    else
      return false;
  }
};