//-*- coding:utf-8 -*-
// Generated by the Fetch-Leetcode project on the Github
// https://github.com/CJHMPower/Fetch-Leetcode/

// 66 Plus One
// https://leetcode.com//problems/plus-one/description/
// Fetched at 2018-07-24
// Submitted 2 years ago
// Runtime: 4 ms
// This solution defeats 3.21% cpp solutions

class Solution {
 public:
  vector<int> plusOne(vector<int>& digits) {
    int i = digits.size() - 1;
    while (i >= 0 && digits[i] == 9) {
      digits[i] = 0;
      i--;
    }
    if (i < 0) {
      digits.insert(digits.begin(), 1);
    } else {
      digits[i]++;
    }
    return digits;
  }
};