//-*- coding:utf-8 -*-
// Generated by the Fetch-Leetcode project on the Github
// https://github.com/CJHMPower/Fetch-Leetcode/

// 14 Longest Common Prefix
// https://leetcode.com//problems/longest-common-prefix/description/
// Fetched at 2018-07-24
// Submitted 2 years ago
// Runtime: 4 ms
// This solution defeats 97.14% cpp solutions

class Solution {
 public:
  string longestCommonPrefix(vector<string>& strs) {
    string result;
    if (strs.empty()) {
      return result;
    }
    int i = 1;
    while (true) {
      if (result.size() >= strs[0].size()) {
        return result;
      }
      char c = strs[0][result.size()];
      i = 1;
      for (; i < strs.size(); i++) {
        if (result.size() >= strs[i].size() || strs[i][result.size()] != c) {
          return result;
        }
      }
      if (i >= strs.size()) {
        result = result + c;
      }
    }
    return result;
  }
};