//-*- coding:utf-8 -*-
// Generated by the Fetch-Leetcode project on the Github
// https://github.com/CJHMPower/Fetch-Leetcode/

// 258 Add Digits
// https://leetcode.com//problems/add-digits/description/
// Fetched at 2018-07-24
// Submitted 5 months ago
// Runtime: 11 ms

class Solution {
 public:
  int addDigits(int num) {
    if (num < 10) {
      return num;
    }
    int ret = 0;
    while (num) {
      ret += num % 10;
      num /= 10;
    }
    return addDigits(ret);
  }
};