//-*- coding:utf-8 -*-
// Generated by the Fetch-Leetcode project on the Github
// https://github.com/CJHMPower/Fetch-Leetcode/

// 258 Add Digits
// https://leetcode.com//problems/add-digits/description/
// Fetched at 2018-07-24
// Submitted 2 years, 1 month ago
// Runtime: 12 ms

class Solution {
 public:
  int addDigits(int num) {
    if (num == 0) {
      return 0;
    }
    return ((int)(num - pow(10, (int)(logf(num) / logf(10)))) % 9 + 1);
  }
};