#-*- coding:utf-8 -*-
#Generated by the Fetch-Leetcode project on the Github
#https://github.com/CJHMPower/Fetch-Leetcode/

#389 Find the Difference
#https://leetcode.com//problems/find-the-difference/description/
#Fetched at 2018-07-24
#Submitted 1 year, 10 months ago
#Runtime: 72 ms
#This solution defeats 1.98% python solutions


class Solution(object):
    def findTheDifference(self, s, t):
        """

        :type s: str

        :type t: str

        :rtype: str

        """

        has = dict()

        for i in t:

            if i not in has:

                has[i] = 1

            else:

                has[i] += 1

        for c in s:

            has[c] -= 1

            if has[c] == 0:

                has.__delitem__(c)

        temp = list(has.keys())

        return temp[0]
