//-*- coding:utf-8 -*-
// Generated by the Fetch-Leetcode project on the Github
// https://github.com/CJHMPower/Fetch-Leetcode/

// 249 Group Shifted Strings
// https://leetcode.com//problems/group-shifted-strings/description/
// Fetched at 2018-07-24
// Submitted 5 months ago
// Runtime: 5 ms
// This solution defeats 4.65% cpp solutions

class Solution {
 public:
  vector<vector<string>> groupStrings(vector<string>& strings) {
    map<vector<int>, vector<string>> hash;
    for (auto word : strings) {
      vector<int> decode(word.size() - 1, 0);
      for (int i = 0; i < word.size() - 1; i++) {
        decode[i] = (int(word[i + 1]) - int(word[i]) + 26) % 26;
      }
      hash[decode].push_back(word);
    }

    vector<vector<string>> ret;
    for (auto it = hash.begin(); it != hash.end(); it++) {
      vector<string> temp;
      for (auto s : it->second) {
        temp.push_back(s);
      }
      ret.push_back(temp);
    }
    return ret;
  }
};