//-*- coding:utf-8 -*-
// Generated by the Fetch-Leetcode project on the Github
// https://github.com/CJHMPower/Fetch-Leetcode/

// 283 Move Zeroes
// https://leetcode.com//problems/move-zeroes/description/
// Fetched at 2018-07-24
// Submitted 5 months, 1 week ago
// Runtime: 17 ms
// This solution defeats 4.89% cpp solutions

class Solution {
 public:
  void moveZeroes(vector<int>& nums) {
    int low = 0, high = 0;
    while (low < nums.size() && high < nums.size()) {
      while (high < nums.size() && nums[low] != 0) {
        low++;
        high++;
      }
      while (high < nums.size() && nums[high] == 0) {
        high++;
      }
      if (high < nums.size()) {
        int b = nums[low];
        nums[low] = nums[high];
        nums[high] = b;
      }
    }
  }
};