//-*- coding:utf-8 -*-
// Generated by the Fetch-Leetcode project on the Github
// https://github.com/CJHMPower/Fetch-Leetcode/

// 283 Move Zeroes
// https://leetcode.com//problems/move-zeroes/description/
// Fetched at 2018-07-24
// Submitted 2 years, 1 month ago
// Runtime: 21 ms
// This solution defeats 2.73% cpp solutions

class Solution {
 public:
  void moveZeroes(vector<int>& nums) {
    int count = 0;
    for (auto it = nums.begin(); it != nums.end();) {
      if (*it == 0) {
        it = nums.erase(it);
        count++;
      } else
        it++;
    }
    for (int i = 0; i < count; i++) {
      nums.push_back(0);
    }
  }
};