//-*- coding:utf-8 -*-
// Generated by the Fetch-Leetcode project on the Github
// https://github.com/CJHMPower/Fetch-Leetcode/

// 409 Longest Palindrome
// https://leetcode.com//problems/longest-palindrome/description/
// Fetched at 2018-07-24
// Submitted 1 year, 9 months ago
// Runtime: 3 ms
// This solution defeats 86.45% cpp solutions

class Solution {
 public:
  int longestPalindrome(string s) {
    vector<int> hash(256, 0);
    for (auto u : s) {
      hash[u]++;
    }
    int result = 0;
    bool flag = false;
    for (int i = 0; i < hash.size(); i++) {
      if (hash[i] % 2 == 0) {
        result += hash[i];
      } else {
        result += (hash[i] - 1);
        flag = true;
      }
    }
    if (flag == true) {
      result += 1;
    }
    return result;
  }
};